### ISSUE TITLE
npm install from git repo subdirectory

### ISSUE THREAD

**Issue by benjamingeorge** [coryhouse/ps-react#10]
First of all your pluralsight course is great!  I'm working on a private company internal component library.  I need to install from our private github account.  I got everything working but when I npm install the library I get the whole source repo, not just what is in the "lib" directory.  I assume this is because I'm not publishing from the lib directory to the NPM registry.  So my question is, is there a way to NPM install from a git repo subdirectory ?  I googled around and there didn't seem to be a clear answer so i though i'd reach out to see if you had any ideas.

**Comment by coryhouse** [comment]
"I assume this is because I'm not publishing from the lib directory to the NPM registry"

Bingo. With the course config, you need to run `npm publish` from the lib directory. This way, only the files that are written to the lib directory are part of your npm package. 

Thanks for the feedback!

**Comment by benjamingeorge** [comment]
What I was referring to was using GIT as a registry and not NPM as I'm not using the `npm publish` command at all. However I understand that this is out of the scope of the course.

**Comment by coryhouse** [comment]
Ah, gotcha. Sorry, I haven't tried that. Why do you want to use Git instead of npm?

**Comment by benjamingeorge** [comment]
We want it to be private and we don't have a private NPM account.

**Comment by coryhouse** [comment]
Ah, we just pay the $7/mo per dev for the private repo. Small price to pay if your team is of reasonable size. But there are many "universal asset repository" alternatives to consider for hosting on premises if you prefer like Proget, Artifactory.

**Comment by benjamingeorge** [comment]
I will look into those suggestions. Thanks again for your time.
