### ISSUE TITLE
Example of PasswordInput has an arrow function inside render method

### ISSUE THREAD

**Issue by sag1v** [coryhouse/ps-react#2]
Hi Cory,
In [ExampleAllFeatures](https://github.com/coryhouse/ps-react/blob/master/src/docs/examples/PasswordInput/ExampleAllFeatures.js) I've noticed that you used an arrow function as a handler of the `onChange` event inside the `render` function.
```
  render() {
    return (
      <div>
        <PasswordInput
          htmlId="password-input-example-all-features"
          name="password"
          onChange={ event => this.setState({ password: event.target.value })}
          value={this.state.password}
          minLength={8}
          placeholder="Enter password"
          showVisibilityToggle
          quality={this.getQuality()}
          {...this.props} />
      </div>
    )
  }
```
Won't it create an instance of this function on each render?
If so, will this pattern provide the same result (while creating one instance of this function)?
```
class ExampleAllFeatures extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      password: ''
    };
    this.handleOnChange = this.handleOnChange.bind(this);
  }

  getQuality() {
    const length = this.state.password.length;
    return length > 10 ? 100 : length * 10;
  }

  handleOnChange(e){
    this.setState({ password: e.target.value })
  }
  render() {
    return (
      <div>
        <PasswordInput
          htmlId="password-input-example-all-features"
          name="password"
          onChange={this.handleOnChange}
          value={this.state.password}
          minLength={8}
          placeholder="Enter password"
          showVisibilityToggle
          quality={this.getQuality()}
          {...this.props} />
      </div>
    )
  }
}

```

**Comment by RIP21** [comment]
@sag1v 
First of all, in your example, you would better use local class variable handleOnChange to not bind it in the constructor to the `this`. Just like that.
```javascript
handleOnChange = (e) => {
    this.setState({ password: e.target.value })
};
```
Second, you are right, every state change a new function will be created. For the sake of example, I think it's fine, but may confuse beginners and promote bad practices.
Also, anonymus functions in the components cause the whole tree of childs to be rerendered, so stuff like 
```javascript
onChange={ () => doSomething() }
``` 
should be avoided and called like
```javascript
onChange={doSomething}
```
instead.

Here is more on that (few tweets)
https://twitter.com/Ives13/status/862676039163621376
And here is the pen that proves that:
https://codesandbox.io/s/D9v9MV4jK

And also an interesting point on passing down not a separate prop, but composed object in this pen:
https://codesandbox.io/s/E42nvAym
Even though property didn't change, object reference changed so it causing a component to rerender.

**Comment by sag1v** [comment]
Thanks @RIP21 .

> you would better use local class variable...

I was sure that this considered experimental.

**Comment by RIP21** [comment]
@sag1v it's experimental stage 2 I think, but if it's supported by create-react-app be sure that its spec is stable enough.

Guys in the CRA team very careful about things that they add into the pack. So, for example decorators `@connect` are not supported since they are on stage 0 or 1, don't remember, but since spec can change dramatically on these stages they didn't add it even though Babel supports is with presets for year or even more.

**Comment by sag1v** [comment]
@RIP21 i didn't know that its on stage 2. do you have any link ref for the specs? i'm having troubles to find it. we are not talking about `static` properties are we?

**Comment by RIP21** [comment]
@sag1v https://github.com/tc39/proposal-class-public-fields/blob/master/README.md
It's on the same spec.

**Comment by sag1v** [comment]
Thanks @RIP21 ! I didn't realize it's on the same spec. will consider to start using them on my projects.

**Comment by coryhouse** [comment]
Thanks for the comments @RIP21. I don't typically use arrows in render in real apps, but for docs I favored brevity over performance. You're right that there's a tradeoff though that people may copy the practice without realizing the potential performance implications. So this was intentional, but I'll add a comment to the course to help clarify. Thanks for the comments guys!

**Comment by coryhouse** [comment]
I just submitted a patch for m6-05 (the clip where I show this code) to display an annotation to help clarify:

"For performance reasons, arrow functions should be avoided in render. I'm just using one here for simplicity." The patch should publish soon, so closing this. Thanks for the input guys!
