### ISSUE TITLE
prop-types package not included in dependencies

### ISSUE THREAD

**Issue by cynx** [coryhouse/ps-react#9]
as per [Migrating from React.PropTypes](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes)  propTypes needs to be explicitly imported from 'prop-types' package. Latter is implemented, however prop-types package is missing from package.json dependencies.

**Comment by coryhouse** [comment]
Ah, good catch! I've updated this repo accordingly, but I'll leave this open until I:
1. Patch the relevant course video
2. Update the course demo that's published under "exercise files".

Thanks!

**Comment by coryhouse** [comment]
Resolved.
